version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laptopsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  node:
    build: ./back
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - ./back:/usr/src/app
    depends_on:
      - db

volumes:
  db_data:
